
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 21 22:21:59 EST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 6;
  public static final int FROM = 5;
  public static final int AND = 7;
  public static final int COMPARISON = 9;
  public static final int SELECT = 3;
  public static final int RPAREN = 15;
  public static final int SEMI = 2;
  public static final int IN = 10;
  public static final int NOT = 8;
  public static final int NAME = 17;
  public static final int LPAREN = 14;
  public static final int STRING = 16;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int DISTINCT = 4;
  public static final int error = 1;
  public static final int DOT = 13;
  public static final int EXISTS = 11;
  public static final int INTNUM = 18;
}

