
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 08 20:17:40 EST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int NUMBER = 9;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int RBRACKET = 6;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int WITH = 7;
  public static final int LBRACKET = 5;
}

